
spring:
  datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/studyweb?serverTimezone=UTC&characterEncoding=UTF-8
      username: root
      password: 1234
  mvc:
      static-path-pattern: /static/**
      resources:
        add-mappings: true
        static-location: classpath:static/
      view:
        prefix: /WEB-INF/views/
        suffix: .jsp



  mybatis:
    type-aliases-package: dan.web.wiki

  thymeleaf:
    cache: false
    check-template-location: true
    mode: HTML5
    order: 0
    prefix: classpath:templates/
    suffix: .html

  devtools:
    livereload:
      enabled: true

  freemarker:
    cache: false
